BusTicketWebApp/Models/Member.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BusTicketWebApp.Models
{
    public class Member
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string PhoneNumber { get; set; }
        public string Email { get; set; }
        public string CreateDate { get; set; }
        public int Status { get; set; }//0:stopped,1:enabled
        public string StatusTxt { get; set; }
        public string LoginPassword { get; set; }
        public string DeviceName { get; set; }
        public string UserAgent { get; set; }
    }
}

BusTicketWebApp/ViewModels/SearchViewModel.cs
using BusTicketWebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BusTicketWebApp.ViewModels
{
    public class SearchViewModel
    {
        public List<PaymentMethod> PaymentMethods { get; set; }
        public List<TicketType> TicketTypes { get; set; }
        public List<TicketStatus> TicketStatus { get; set; }
    }
}

BusTicketWebApp/Controllers/MemberController.cs
using BusTicketWebApp.Dtos;
using BusTicketWebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Web;
using System.Web.Mvc;
using BusTicketWebApp.ViewModels;
using Newtonsoft.Json;

namespace BusTicketWebApp.Controllers
{
    public class MemberController : Controller
    {
        private readonly string _baseAddressOrder = "http://b-rc-api-busticket-mgr.azurewebsites.net/api/";

        // GET: Member
        public ActionResult Index()
        {
            return View();
        }

        // GET: Member
        public ActionResult Search()
        {
            if (Session["email"] == null)
            {
                return RedirectToAction("Index", "User");
            }
            Session["show"] = null;

            return View();
        }
        [HttpGet]
        public ActionResult SearchResult()
        {
            Session["show"] = null;
            return View();
        }
        [HttpPost]
        public ActionResult SearchResult(FormCollection fc)
        {
            if (Session["email"] == null)
            {
                return RedirectToAction("Index", "User");
            }
            Session["show"] = null;

            MemberSearchDto memberSearchDto = new MemberSearchDto();
            //Order search = new Order();
            List<MemberList> searchLists = new List<MemberList>();
            memberSearchDto.FromDate = "";
            if (!string.IsNullOrEmpty(fc["r_fromDate"]))
            {
                memberSearchDto.FromDate = fc["r_fromDate"];
            }
            memberSearchDto.ToDate = "";
            if (!string.IsNullOrEmpty(fc["r_toDate"]))
            {
                memberSearchDto.ToDate = fc["r_toDate"];
            }
            memberSearchDto.Email = "";
            if (!String.IsNullOrEmpty(fc["user_email"]))
            {
                memberSearchDto.Email = fc["user_email"];
            }
            memberSearchDto.StatusId = "";
            if (!String.IsNullOrEmpty(fc["status"]))
            {
                memberSearchDto.StatusId = fc["status"];
            }
            memberSearchDto.LastName = "";
            if (!String.IsNullOrEmpty(fc["last_name"]))
            {
                memberSearchDto.LastName = fc["last_name"];
            }
            memberSearchDto.FirstName = "";
            if (!String.IsNullOrEmpty(fc["first_name"]))
            {
                memberSearchDto.FirstName = fc["first_name"];
            }
            memberSearchDto.PhoneNumber = "";
            if (!String.IsNullOrEmpty(fc["phone"]))
            {
                memberSearchDto.PhoneNumber = fc["phone"];
            }
            memberSearchDto.MemberId = "";
            if (!String.IsNullOrEmpty(fc["member_id"]))
            {
                memberSearchDto.MemberId = fc["member_id"];
            }
            memberSearchDto.FromToRegDate = "";
            if (!String.IsNullOrEmpty(fc["r_from_to_Date"]))
            {
                memberSearchDto.FromToRegDate = fc["r_from_to_Date"];
            }
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(_baseAddressOrder);

                //HTTP POST
                var postTask = client.PostAsJsonAsync<MemberSearchDto>("Users", memberSearchDto);
                postTask.Wait();

                var result = postTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<List<MemberList>>();

                    searchLists = readTask.Result;

                }
            }

            ViewBag.Status = GetTicketStatus();

            return View(searchLists);
        }
        public ActionResult MemberDetails(int id)
        {
            if (Session["email"] == null)
            {
                return RedirectToAction("Index", "User");
            }

            Member member = new Member();
            Session["show"] = "display";

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(_baseAddressOrder);
                //HTTP GET
                var responseTask = client.GetAsync("Users/" + id);
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {

                    var readTask = result.Content.ReadAsAsync<Member>();
                    readTask.Wait();

                    member = readTask.Result;
                }

            }

            if (Convert.ToInt32(member.Status) == 1)
            {
                member.StatusTxt = "Enabled";
            }
            else
            {
                member.StatusTxt = "Stopped";
            }

            return View(member);
        }
        public List<TicketStatus> GetTicketStatus()
        {
            List<TicketStatus> _ticketStatus = new List<TicketStatus>();
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(_baseAddressOrder);
                //HTTP GET
                var responseTask = client.GetAsync("utl/utilities/ticketstatus/");
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {

                    var readTask = result.Content.ReadAsAsync<List<TicketStatus>>();
                    readTask.Wait();

                    _ticketStatus = readTask.Result;
                }

            }
            return _ticketStatus;
        }

        public ActionResult MemberHistory(string Id)
        {
            if (Session["email"] == null)
            {
                return RedirectToAction("Index", "User");
            }
            Session["show"] = null;
            List<MemberHistoryList> objMemberHistoryList = new List<MemberHistoryList>();

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(_baseAddressOrder);

                //HTTP POST
                var responseTask = client.GetAsync("utl/utilities/UserHistory/" + Id);
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<List<MemberHistoryList>>();

                    objMemberHistoryList = readTask.Result;

                }
            }

            ViewBag.UserId = Id;

            return View(objMemberHistoryList);
        }
        [HttpPost]
        public JsonResult DeleteMember(string updateData)
        {
            MemberUpdateDto updateObjectMessage = null;

            var data = JsonConvert.DeserializeObject<DataConversionForUpdate>(updateData);
            try
            {
                using (var client = new HttpClient())
                {
                    client.BaseAddress = new Uri(_baseAddressOrder);

                    //HTTP DELETE
                    var putTask = client.DeleteAsync("users/" + data.Id);
                    putTask.Wait();

                    var result = putTask.Result;
                    if (result.IsSuccessStatusCode)
                    {
                        var readTask = result.Content.ReadAsAsync<MemberUpdateDto>();

                        updateObjectMessage = readTask.Result;

                    }
                }
            }
            catch (Exception e)
            {

            }
            return Json(updateObjectMessage, JsonRequestBehavior.AllowGet);
        }

        [HttpPost]
        public JsonResult UpdateMember(string updateData)
        {
            MemberUpdateDto objMemberUpdateDto = null;

            DataConversionForUpdate data = JsonConvert.DeserializeObject<DataConversionForUpdate>(updateData);


            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(_baseAddressOrder);

                //HTTP PUT
                var putTask = client.PutAsJsonAsync<DataConversionForUpdate>("Users", data);
                putTask.Wait();

                var result = putTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<MemberUpdateDto>();

                    objMemberUpdateDto = readTask.Result;

                }
            }

            return Json(objMemberUpdateDto, JsonRequestBehavior.AllowGet);
        }
        public class DataConversionForUpdate
        {
            public string Id { get; set; }
            public string FirstName { get; set; }
            public string LastName { get; set; }
            public string Email { get; set; }
            public string PhoneNumber { get; set; }
        }

        [HttpPost]
        public JsonResult AlterMemberStatus(string orderdata, string statusId)
        {
            MemberUpdateDto objMemberUpdate = null;
            
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(_baseAddressOrder);

                //HTTP DELETE
                var putTask = client.PutAsJsonAsync<string>("utl/utilities/AlterUserStatus?statusId=" + statusId + "&userIds=" + orderdata, "");
                putTask.Wait();

                var result = putTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<MemberUpdateDto>();

                    objMemberUpdate = readTask.Result;

                }
            }
            return Json(objMemberUpdate, JsonRequestBehavior.AllowGet);
        }

    }
}

BusTicketWebApp/Views/Member/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h2>Index</h2>

BusTicketWebApp/Views/Member/MemberHistory.cshtml
@model IEnumerable<BusTicketWebApp.Models.MemberHistoryList>

@{
    ViewBag.Title = "SearchResult";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Html.Partial("_LeftMenu")


<style>
    .page-navigation {
        border: none;
        outline: none;
        padding: 10px 16px;
        background-color: #f1f1f1;
        cursor: pointer;
    }
</style>
<br />
<nav>
    @{
        string pageName = HttpContext.Current.Request.Url.AbsoluteUri;

        <a href="/Orders" class="page-navigation"><span class="glyphicon glyphicon-home"></span> Top Page</a>
        <span class="glyphicon glyphicon-forward"></span>
        <a href="/Member/Search" class="page-navigation">Member Search</a>
        <span class="glyphicon glyphicon-forward"></span>

        if (pageName.ToLower().IndexOf("memberhistory") >= 0)
        {
            <a href="/Member/MemberHistory" style="pointer-events: none;  cursor: default;" class="page-navigation">Member History</a>
        }
        else
        {
            <a href="/Member/MemberHistory" class="page-navigation">Member History</a>
        }
    }
</nav>

<br /><br />
<div class="col-xs-10">
    <div class="row">
        <div class="col-xs-3">
            <h2>Updated History</h2>
        </div>
    </div>
    <br />
    <div class="row">
        @*<div class="col-xs-3">
                Updated On: <label style="color:#1281c9;">05-Sept-2022</label>
            </div>*@
        <div class="col-xs-3">
            <p id="date_time_today"><i class="fa fa-calendar" aria-hidden="true"></i>  @DateTime.Now.ToString("dd/MM/yyyy") (@DateTime.Now.DayOfWeek)</p>
        </div>
        <div class="col-xs-2">
            <p id="date_time_today"><i class="" aria-hidden="true"></i>User:  Admin Super</p>
        </div>
        @*<div class="col-xs-3">
                User: <label style="color:#1281c9;">Admin Super</label>
            </div>*@
    </div>

    <div class="row">
        <div class="col-xs-3">
            <h3 style="color:#0f49a0;">Member History</h3>
        </div>
        <table class="table" id="search_result_table">
            <caption>Specific members updated history</caption>
            <thead style="background-color:beige;">
                <tr>
                    <th scope="col">SL</th>
                    <th scope="col" style="color:#004ba6;">Registration Date</th>
                    <th scope="col" style="color:#004ba6;">Updated Date</th>
                    <th scope="col" style="color:#004ba6;">First Name</th>
                    <th scope="col" style="color:#004ba6;">Last Name</th>
                    <th scope="col" style="color:#004ba6;">Telephone</th>
                    <th scope="col" style="color:#004ba6;">Email</th>
                    <th scope="col" style="color:#004ba6;">Status</th>
                </tr>
            </thead>
            <tbody>
                @{

                    int count = 1;
                    foreach (var item in Model)
                    {
                        <tr>
                            <th scope="row">@count</th>
                            <td>@Convert.ToDateTime(item.CreateDate)</td>
                            <td>@Convert.ToDateTime(item.UpdateDate)</td>
                            <td>@item.FirstName</td>
                            <td>@item.LastName</td>
                            <td>@item.PhoneNumber</td>
                            <td>@item.Email</td>
                            @{
                                string strStatus = "";
                                if (item.Status == 2 || item.Status == 0)
                                {
                                    strStatus = "Stopped (Inactive)";
                                }
                                else if (item.Status == 1)
                                {
                                    if (count == 1)
                                    {
                                        strStatus = "Enabled (Active)";
                                    }
                                    else
                                    {
                                        strStatus = "Enabled (Inactive)";
                                    }
                                }

                                //if (Convert.ToInt32(item.Status) == 1)
                                //{
                                //    strStatus = "Enabled";
                                //}
                                //else if (Convert.ToInt32(item.Status) == 1)
                                //{
                                //    strStatus = "Stopped";
                                //}
                                <td>@strStatus</td>
                            }
                        </tr>
                        count++;
                    }
                }
            </tbody>
        </table>
        <hr />
    </div>

</div>

@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $('#search_result_table').DataTable({
                //pagingType: 'full_numbers',
                pagingType: 'input',
                //dom: '<"top"iflp<"clear">>rt<"bottom"iflp<"clear">>',
                dom: 'lifrtip',
                //pageLength: 5,
                aLengthMenu: [
                    [10, 25, 50, 100, 200, -1],
                    [10, 25, 50, 100, 200, "All"]
                ],
                language: {
                    oPaginate: {
                        sNext: '<i class="fa fa-forward"></i>',
                        sPrevious: '<i class="fa fa-backward"></i>',
                        sFirst: '<i class="fa fa-step-backward"></i>',
                        sLast: '<i class="fa fa-step-forward"></i>'
                    }
                }
            });


            $('#select_all_check_box').on('click', function () {
                var check_all_value = $('#select_all_check_box').is(':checked');
                if (check_all_value) {
                    $('#search_result_table input:checkbox').prop('checked', check_all_value);
                }
                else {
                    $('#search_result_table input:checkbox').prop('checked', check_all_value);
                }
            });


            $('#search_result_table').on('click', '.o_details', function () {

                var id = $(this).data('id');
                var url = $(this).data('url') + '/' + id;
                console.log(url);
                $.get(url, function (data) {
                    $('#order_details_modal_body').html(data);
                    $('#order_details_modal').modal('show');
                });
            })



        });
    </script>
    <script src="https://cdn.datatables.net/plug-ins/1.12.1/pagination/input.js"></script>
}

BusTicketWebApp/Views/Member/SearchResult_10Sept2022.cshtml
@model IEnumerable<BusTicketWebApp.Models.MemberList>

@{
    ViewBag.Title = "Member List";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Html.Partial("_LeftMenu")

<div class="col-xs-10">
    <div class="row">
        <div class="col-xs-3 search_result_nav_div">
            <h4>Search Results</h4>
        </div>
        <div class="col-xs-offset-6 col-xs-2 date_time_today_div">
            <p id="date_time_today"><i class="fa fa-calendar" aria-hidden="true"></i>  @DateTime.Now.ToString("dd/MM/yyyy") (@DateTime.Now.DayOfWeek)</p>
        </div>
    </div>

    <div class="row">
        <div class="search_table">
            <input type="checkbox" id="select_all_check_box" /> Select All
            <table class="table table-bordered" id="search_result_table">
                <thead>
                    <tr>
                        <th></th>
                        <th scope="col">#</th>
                        <th scope="col">Member Id</th>
                        <th scope="col">Registration Date</th>
                        <th scope="col">Name</th>
                        <th scope="col">Email</th>
                        <th>Phone</th>
                        <th>Status</th>
                        <th>Total Purchase</th>
                        <th scope="col">Member History</th>
                        <th scope="col">Member Details</th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        int count = 1;
                        foreach (var x in Model)
                        {
                    <tr>
                        <td><input type="checkbox" id="single_checkbox_@x.Id" value="@x.Id" name="ck_change" data-status="@x.Id" /></td>
                        <td>@count</td>
                        <td><a href="javascript:void();">@x.Id</a></td>
                        @*<td>@x.CreateDate</td>*@
                        <td>@Convert.ToDateTime(x.CreateDate).ToString("dddd, dd MMMM yyyy")</td>
                        <td>@x.FirstName @x.LastName</td>
                        <td><a href="javascript:void()">@x.Email</a><a href="mailto: @x.Email" style="display:block;padding:5px"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span></a></td>
                        <td>@x.PhoneNumber</td>
                        @{
                            string memberStatus = "";
                            if (x.Status == 1)
                            {
                                memberStatus = "Enabled";
                            }
                            else
                            {
                                memberStatus = "Stopped";
                            }
                        }
                        <td style="color:green;">@memberStatus</td>
                        <td>@x.TotalPurchase</td>
                        <td><a href="javascript:void(0);" class="o_details" data-id="@x.Id" data-url='@Url.Action("MemberDetails","Member")'>History</a></td>
                        <td><a href="javascript:void(0);" class="o_details" data-id="@x.Id" data-url='@Url.Action("MemberDetails","Member")'>Details</a></td>
                    </tr>
                            count++;
                        }
                    }

                </tbody>
            </table>

        </div>
    </div>

    <div class="row">
        <div class="col-xs-12 status_chang_div">
            <div class="col-xs-12">
                <p style="font-weight:bold">Change Status</p>
            </div>
            <div class="col-xs-3">

                <select class="form-control" id="status_change_sl">
                    <option value="">Select Status</option>
                    @*@foreach (var item in ViewBag.Status)
                        {
                            <option value="@item.Id">@item.statusName</option>
                        }*@
                    <option value="1">Enabled</option>
                    <option value="2">Stopped</option>
                </select>
            </div>
            <div class="col-xs-2">
                <button id="status_change_btn" class="btn btn-info">change</button>
            </div>
            @*<div class="col-lg-offset-5 col-xs-1">
                    <a href="/Orders/GenerateSearchPdf?OrderFromDate=@ViewBag.OrderFromDate&OrderToDate=@ViewBag.OrderToDate&OrderNo=@ViewBag.OrderNo&Type=@ViewBag.Type&GmoOrderNo=@ViewBag.GmoOrderNo&PaymentMethod=@ViewBag.PaymentMethod&LastName=@ViewBag.LastName&FirstName=@ViewBag.FirstName&Status=@ViewBag.StatusId&Telephone=@ViewBag.Telephone&Email=@ViewBag.Email" id="status_change_btn" class="btn btn-default"><i class="fa fa-print" aria-hidden="true"></i> Print PDF</a>
                </div>
                <div class="col-xs-1">
                    <a href="/Orders/GenerateSearchCsv?OrderFromDate=@ViewBag.OrderFromDate&OrderToDate=@ViewBag.OrderToDate&OrderNo=@ViewBag.OrderNo&Type=@ViewBag.Type&GmoOrderNo=@ViewBag.GmoOrderNo&PaymentMethod=@ViewBag.PaymentMethod&LastName=@ViewBag.LastName&FirstName=@ViewBag.FirstName&Status=@ViewBag.StatusId&Telephone=@ViewBag.Telephone&Email=@ViewBag.Email" id="status_change_btn" class="btn btn-default"><i class="fa fa-print" aria-hidden="true"></i> Print CSV </a>
                </div>*@
        </div>
    </div>

    <div class="row">
        <div class="col-xs-offset-2 col-xs-7">
            <div class="modal fade" id="order_details_modal" role="dialog">
                @*</div>*@
                <!-- The modal -->
                @*<div class="modal fade" id="flipFlop" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">*@
                <div class="modal-dialog" role="document">
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                <span aria-hidden="true">&times;</span>
                            </button>
                            <h4 class="modal-title" id="modalLabel">Member Details</h4>
                        </div>
                        <div class="modal-body" id="order_details_modal_body">

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {

            var selected_rows = [];
            //$('#search_result_table').dataTable();
            $('#search_result_table').DataTable({
                //pagingType: 'full_numbers',
                pagingType: 'input',
                //dom: '<"top"iflp<"clear">>rt<"bottom"iflp<"clear">>',
                dom: 'lifrtip',
                //pageLength: 5,
                language: {
                    oPaginate: {
                        sNext: '<i class="fa fa-forward"></i>',
                        sPrevious: '<i class="fa fa-backward"></i>',
                        sFirst: '<i class="fa fa-step-backward"></i>',
                        sLast: '<i class="fa fa-step-forward"></i>'
                    }
                }
            });

            $('#select_all_check_box').on('click', function () {
                var check_all_value = $('#select_all_check_box').is(':checked');
                if (check_all_value) {
                    $('#search_result_table input:checkbox').prop('checked', check_all_value);
                }
                else {
                    $('#search_result_table input:checkbox').prop('checked', check_all_value);
                }
            });


            $('#search_result_table').on('click', '.o_details', function () {

                var id = $(this).data('id');
                var url = $(this).data('url') + '/' + id;
                console.log(url);
                $.get(url, function (data) {
                    $('#order_details_modal_body').html(data);
                    $('#order_details_modal').modal('show');
                });
            });

            function ChangeOrderStatus(selectedOrderAsString, valueOfSelect) {
                $.confirm({
                    title: 'Confirm!',
                    content: 'Change Status?',
                    buttons: {
                        confirm: function () {

                        //if (selected_rows.length > 0) {
                            $.ajax({
                                type: 'POST',
                                url: '@Url.Action("AlterOrderStatus", "Orders")',
                                data: {
                                    orderdata: selectedOrderAsString,
                                    statusId : valueOfSelect
                                },
                                success: function (data) {
                                    console.log(data);
                                    if (data.Status == 'ok') {

                                        $.alert({
                                            title: 'Success!!!',
                                            content: data.Message,
                                        });
                                        location.reload(true);
                                    }
                                    else {
                                        $.alert({
                                            title: 'Failed!!!',
                                            content: data.Message,
                                        });
                                        location.reload(true);
                                    }
                                },
                                complete: {
                                }
                            });
                        },
                        cancel: function () {
                            //$.alert('Canceled!');
                        },
                    }
                });
            }

            $('#status_change_btn').on('click', function () {
                selected_rows = [];
                let selectedOrderAsString = '';

                $("#search_result_table tbody tr td input:checkbox[name=ck_change]:checked").each(function () {
                    selected_rows.push($(this).val());
                });

                var valueOfSelect = $('#status_change_sl').val();
                if (valueOfSelect == null || valueOfSelect == "") {
                    alert("Select Status");
                    return false;
                    modal.dis
                }
                else if (selected_rows.length <= 0) {
                    alert("Select Order");
                    return false;
                }
                else if (valueOfSelect == "5") {
                    selected_rows = [];
                    $("#search_result_table tbody tr td input:checkbox[name=ck_change]:checked").each(function () {
                        var elementVal = $(this).attr('data-status');

                        if (elementVal == "1" || elementVal == "2") {
                            selected_rows.push($(this).val());
                            selectedOrderAsString += $(this).val() + ",";
                        }
                        else {
                            $(this).prop('checked', false);
                        }

                    });
                }
                else {
                    selected_rows = [];
                    $("#search_result_table tbody tr td input:checkbox[name=ck_change]:checked").each(function () {
                        selected_rows.push($(this).val());
                        selectedOrderAsString += $(this).val() + ",";
                    });
                }
                ChangeOrderStatus(selectedOrderAsString, valueOfSelect);

            });

        });
    </script>

    <script src="https://cdn.datatables.net/plug-ins/1.12.1/pagination/input.js"></script>
}