BusTicketWebApp/Models/Order.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BusTicketWebApp.Models
{
    public class Order
    {
        public int Id { get; set; }
        public int ElectronicTicketId { get; set; }
        public DateTime BoardingDate { get; set; }
        public string ExpiredAt { get; set; }
        public DateTime OrderDate { get; set; }
        public string Route { get; set; }
        public string OrderNo { get; set; }
        public string Type { get; set; }
        public string GmoOrderNo { get; set; }
        public string Flight { get; set; }
        public string PaymentMethod { get; set; }
        public string BoardingPlace { get; set; }
        public string MemberId { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Status { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }

        public int TicketTypeId { get; set; }

        public string TicketName { get; set; }

        public int PaymentMethodType { get; set; }

        public string DeviceType { get; set; }
        public string DeviceName { get; set; }
        public string UserAgent { get; set; }

        public int NumberOfAdult { get; set; }

        public int NumberOfChild { get; set; }

        public decimal TotalPrice { get; set; }

        public decimal PriceForAdult { get; set; }

        public decimal PriceForChild { get; set; }

        public string UserId { get; set; }

        public decimal CancellationFee { get; set; }

        // extra columns for search orders
        public DateTime? BoardingFromDate { get; set; }
        public DateTime? BoardingToDate { get; set; }
        public DateTime? OrderFromDate { get; set; }
        public DateTime? OrderToDate { get; set; }

        public string OrderDateFromTo { get; set; }
        public string DateOfUseFrom { get; set; }
        public string DateOfUseTo { get; set; }
        public string DateOfuse_From_To { get; set; }
        public string OrderIds { get; set; }
    }
}

BusTicketWebApp/ViewModels/OrderHistoryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BusTicketWebApp.ViewModels
{
    public class OrderHistoryViewModel
    {
        public int OrderId { get; set; }
        public string OrderNo { get; set; }
        public string OrderDate { get; set; }
        public string UpdatedAt { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Telephone { get; set; }
        public string Email { get; set; }
        public int Adult { get; set; }
        public int Child { get; set; }
        public decimal Price { get; set; }
        public string Status { get; set; }
    }
}

BusTicketWebApp/ViewModels/OrderViewModel.cs
using BusTicketWebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BusTicketWebApp.ViewModels
{
    public class OrderViewModel
    {
        public Order Order { get; set; }
        public List<PaymentMethod> PaymentMethods { get; set; }
        public List<TicketType> TicketTypes { get; set; }

        public List<int> Childs { get; set; }

        public List<int> Adults { get; set; }
    }
}

BusTicketWebApp/ViewModels/SearchViewModel.cs
using BusTicketWebApp.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace BusTicketWebApp.ViewModels
{
    public class SearchViewModel
    {
        public List<PaymentMethod> PaymentMethods { get; set; }
        public List<TicketType> TicketTypes { get; set; }
        public List<TicketStatus> TicketStatus { get; set; }
    }
}

BusTicketWebApp/Controllers/OrdersController.cs
using BusTicketWebApp.Dtos;
using BusTicketWebApp.Models;
using BusTicketWebApp.ViewModels;
using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using System.Threading.Tasks;
using System.Web;
using System.Web.Mvc;
using System.Web.Script.Serialization;
using iText.Html2pdf;
using iText.Kernel.Pdf;
using iText.Kernel.Geom;
using iText.Layout;

namespace BusTicketWebApp.Controllers
{
    public class OrdersController : Controller
    {
        private readonly string _baseAddressOrder = "http://b-rc-api-busticket-mgr.azurewebsites.net/api/";
        // GET: Orders
        public ActionResult Index()
        {
            //sudipto
            if (Session["email"] == null)
            {
                return RedirectToAction("Index", "User");
            }
            Session["show"] = null;
            return View();
        }

        public ActionResult Search()
        {
            if (Session["email"] == null)
            {
                return RedirectToAction("Index", "User");
            }
            Session["show"] = null;
            SearchViewModel searchViewModel = new SearchViewModel
            {
                TicketStatus = GetTicketStatus(),
                PaymentMethods = GetPaymentMethods(),
                TicketTypes = GetTicketTypes(),
            };
            return View(searchViewModel);
        }

        [HttpPost]
        public ActionResult SearchResult(FormCollection fc)
        {
            if (Session["email"] == null)
            {
                return RedirectToAction("Index", "User");
            }
            Session["show"] = null;
            OrderSearchDto searchDto = new OrderSearchDto();
            Order search = new Order();
            List<SearchList> searchLists = new List<SearchList>();
            //if (!String.IsNullOrEmpty(fc["b_fromDate"]))
            //{
            //    search.BoardingFromDate = Convert.ToDateTime(fc["b_fromDate"]);
            //}
            //if (!String.IsNullOrEmpty(fc["b_toDate"]))
            //{
            //    search.BoardingToDate = Convert.ToDateTime(fc["b_toDate"]);
            //}
            //if (fc["route"] != null)
            //{
            //    search.Route = fc["route"];
            //}
            if (fc["type"] != null)
            {
                searchDto.Type = fc["type"];
            }
            //if (!String.IsNullOrEmpty(fc["flight"]))
            //{
            //    search.Flight = fc["flight"];
            //}
            //if (!String.IsNullOrEmpty(fc["boarding_place"]))
            //{
            //    search.BoardingPlace = fc["boarding_place"];
            //}
            if (!String.IsNullOrEmpty(fc["status"]))
            {
                searchDto.Status = fc["status"];
            }
            if (!String.IsNullOrEmpty(fc["o_fromDate"]))
            {
                searchDto.OrderFromDate = fc["o_fromDate"];
            }
            if (!String.IsNullOrEmpty(fc["o_toDate"]))
            {
                searchDto.OrderToDate = fc["o_toDate"];
            }
            if (!String.IsNullOrEmpty(fc["order_no"]))
            {
                searchDto.OrderNo = fc["order_no"];
            }
            if (!String.IsNullOrEmpty(fc["gmo_order_no"]))
            {
                searchDto.GmoOrderNo = fc["gmo_order_no"];
            }

            if (!String.IsNullOrEmpty(fc["payment_method"]))
            {
                searchDto.PaymentMethodType = fc["payment_method"];
            }
            if (!String.IsNullOrEmpty(fc["member_id"]))
            {
                searchDto.MemberId = fc["member_id"];
            }
            if (!String.IsNullOrEmpty(fc["last_name"]))
            {
                searchDto.LastName = fc["last_name"];
            }
            if (!String.IsNullOrEmpty(fc["first_name"]))
            {
                searchDto.FirstName = fc["first_name"];
            }
            if (!String.IsNullOrEmpty(fc["telephone"]))
            {
                searchDto.Telephone = fc["telephone"];
            }
            if (!String.IsNullOrEmpty(fc["email"]))
            {
                searchDto.Email = fc["email"];
            }
            if (!String.IsNullOrEmpty(fc["o_routes"]))
            {
                searchDto.RoutesId = fc["o_routes"];
            }
            if (!String.IsNullOrEmpty(fc["order_flight"]))
            {
                searchDto.FlightId = fc["order_flight"];
            }
            if (!String.IsNullOrEmpty(fc["b_fromDate"]))
            {
                searchDto.DateOfUseFrom = fc["b_fromDate"];
            }
            if (!String.IsNullOrEmpty(fc["b_toDate"]))
            {
                searchDto.DateOfUseTo = fc["b_toDate"];
            }
            if (!String.IsNullOrEmpty(fc["b_from_to_date"]))
            {
                searchDto.DateOfuse_From_To = fc["b_from_to_date"];
            }
            if (!String.IsNullOrEmpty(fc["o_From_To_Date"]))
            {
                searchDto.OrderDateFromTo = fc["o_From_To_Date"];
            }
            if (!String.IsNullOrEmpty(fc["IsViewDownload"]))
            {
                searchDto.IsViewDownload = fc["IsViewDownload"];
            }
            if (!String.IsNullOrEmpty(fc["OrderIdsView"]))
            {
                searchDto.OrderIds = fc["OrderIdsView"];
            }

            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(_baseAddressOrder);

                //HTTP POST
                var postTask = client.PostAsJsonAsync<OrderSearchDto>("orders", searchDto);
                postTask.Wait();

                var result = postTask.Result;
                if (result.IsSuccessStatusCode)
                {
                    var readTask = result.Content.ReadAsAsync<List<SearchList>>();

                    searchLists = readTask.Result;

                }
            }



            //ViewBag.BoardingFromDate = search.BoardingFromDate;
            //ViewBag.BoardingToDate = search.BoardingToDate;
            ViewBag.OrderFromDate = searchDto.OrderFromDate;
            ViewBag.OrderToDate = searchDto.OrderToDate;
            ViewBag.OrderDateFromTo = searchDto.OrderDateFromTo;
            //ViewBag.Route = search.Route;
            ViewBag.OrderNo = searchDto.OrderNo;
            ViewBag.Type = searchDto.Type;
            ViewBag.GmoOrderNo = searchDto.GmoOrderNo;
            //ViewBag.Flight = search.Flight;
            ViewBag.PaymentMethod = searchDto.PaymentMethodType;
            //ViewBag.BoardingPlace = search.BoardingPlace;
            ViewBag.MemberId = search.MemberId;
            ViewBag.LastName = searchDto.LastName;
            ViewBag.FirstName = searchDto.FirstName;
            ViewBag.StatusId = searchDto.Status;
            ViewBag.Telephone = searchDto.Telephone;
            ViewBag.Email = searchDto.Email;
            ViewBag.FormEmail = searchDto.Email;
            ViewBag.DateOfUseFrom = searchDto.DateOfUseFrom;
            ViewBag.DateOfUseTo = searchDto.DateOfUseTo;
            ViewBag.DateOfuse_From_To = searchDto.DateOfuse_From_To;
            ViewBag.RoutesId = searchDto.RoutesId;
            ViewBag.FlightId = searchDto.FlightId;
            ViewBag.OrderIds = searchDto.OrderIds;


            if (!string.IsNullOrEmpty(searchDto.IsViewDownload))
            {
                ViewBag.IsViewDownload = searchDto.IsViewDownload;
            }
            else
            {
                ViewBag.IsViewDownload = "no";
            }

            ViewBag.Status = GetTicketStatus();

            ViewBag.UserId = searchDto.MemberId;
            if (!string.IsNullOrEmpty(ViewBag.UserId))
            {
                if (Convert.ToInt32(ViewBag.UserId) > 0)
                {
                    //int tempCount = 1;
                    foreach (var x in searchLists)
                    {
                        ViewBag.Name = x.Purchaser;
                        ViewBag.Email = x.Email;
                        //if(searchDto.MemberId == x.UserId)
                        //{
                        ViewBag.UserStatus = x.MemberStatus;
                        //}                        
                    }
                }
            }
            //ViewBag.UserStatus = x.MemberStatus;
            //

            return View(searchLists);
        }


        public ActionResult OrderDetails(int id, int status)
        {
            if (Session["email"] == null)
            {
                return RedirectToAction("Index", "User");
            }

            Order order = null;
            Session["show"] = "display";
            using (var client = new HttpClient())
            {
                client.BaseAddress = new Uri(_baseAddressOrder);
                //HTTP GET
                var responseTask = client.GetAsync("orders/" + id);
                responseTask.Wait();

                var result = responseTask.Result;
                if (result.IsSuccessStatusCode)
                {

                    var readTask = result.Content.ReadAsAsync<Order>();
                    readTask.Wait();

                    order = readTask.Result;
                }
            }


            OrderViewModel orderViewModel = new OrderViewModel
            {
                Order = order,
                PaymentMethods = Utility.GetPaymentMethods(),
                TicketTypes = Utility.GetTicketTypes(),
                Adults = Utility.GetAdultNumbers(),
                Childs = Utility.GetChildNumbers(),
            };

            ViewBag.OrderId = id;
            ViewBag.MemberStatus = status;
            string strMemberStatus = "";
            if (status == 1)
            {
                strMemberStatus = "Enabled";
            }
            else
            {
                strMemberStatus = "Stopped";

BusTicketWebApp/Views/Orders/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Html.Partial("_LeftMenu")
<h2>Application Top Page</h2>

BusTicketWebApp/Views/Orders/OrderHistory_3Sept2022.cshtml
@model BusTicketWebApp.ViewModels.OrderViewModel

@{
    /**/

    ViewBag.Title = "SearchResult";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Html.Partial("_LeftMenu")

<div class="col-xs-10">
    <div class="row">
        <div class="col-xs-3">
            <h2>Order Details</h2>
        </div>
    </div>
    <br />
    <div class="row">
        <div class="col-xs-3">
            Updated On: <label style="color:#1281c9;">@Model.Order.OrderDate</label>
        </div>
        <div class="col-xs-3">
            User: <label style="color:#1281c9;">Admin Super</label>
        </div>
    </div>

    <div class="row">
        <div class="col-xs-3">
            <h3 style="color:#0f49a0;">Basic Information</h3>
        </div>
        <table class="table">
            <thead style="background-color:beige;">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col" style="color:#004ba6;">Order No</th>
                    <th scope="col" style="color:#004ba6;">Customer Name</th>
                    <th scope="col" style="color:#004ba6;">GMO Order Id</th>
                    <th scope="col" style="color:#004ba6;">Email</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">1</th>
                    <td>@Model.Order.OrderNo</td>
                    <td>@Model.Order.FirstName @Model.Order.LastName</td>
                    <td>@Model.Order.GmoOrderNo</td>
                    <td>@Model.Order.Email</td>
                </tr>
            </tbody>
        </table>
        <hr />
    </div>

    <div class="row">
        <div class="col-xs-3">
            <h3 style="color:#0f49a0;">Order Information</h3>
        </div>
        <table class="table">
            <thead style="background-color:beige;">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col" style="color:#004ba6;">Order Date</th>
                    <th scope="col" style="color:#004ba6;">Expire Date</th>
                    <th scope="col" style="color:#004ba6;">Adult</th>
                    <th scope="col" style="color:#004ba6;">Child</th>
                    <th scope="col" style="color:#004ba6;">Status</th>
                    <th scope="col" style="color:#004ba6;">Cancelation fee</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <th scope="row">1</th>
                    <td>@Model.Order.OrderDate</td>
                    <td>@Model.Order.ExpiredAt</td>
                    <td>@Model.Order.NumberOfAdult</td>
                    <td>@Model.Order.NumberOfChild</td>

                    @if (Model.Order.Status == "1")
                    {
                        <td><span class="text-primary-custom">Before</span></td>
                    }
                    else if (Model.Order.Status == "2")
                    {
                        <td><span class="text-info-custom">In Use</span></td>
                    }
                    else if (Model.Order.Status == "3")
                    {
                        <td><span class="text-success-custom">Used</span></td>
                    }
                    else if (Model.Order.Status == "4")
                    {
                        <td><span class="text-warning-custom">Expired</span></td>
                    }
                    else
                    {
                        <td><span class="text-muted-custom">Cancelled</span></td>
                    }

                    <td>@Model.Order.CancellationFee</td>
                </tr>
            </tbody>
        </table>
        <hr />
    </div>

</div>

@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            $('#search_result_table').dataTable()


            $('#select_all_check_box').on('click', function () {
                var check_all_value = $('#select_all_check_box').is(':checked');
                if (check_all_value) {
                    $('#search_result_table input:checkbox').prop('checked', check_all_value);
                }
                else {
                    $('#search_result_table input:checkbox').prop('checked', check_all_value);
                }
            });


            $('#search_result_table').on('click', '.o_details', function () {

                var id = $(this).data('id');
                var url = $(this).data('url') + '/' + id;
                console.log(url);
                $.get(url, function (data) {
                    $('#order_details_modal_body').html(data);
                    $('#order_details_modal').modal('show');
                });
            })



        });
    </script>
}

BusTicketWebApp/Views/Orders/SearchResult_20Aug22.cshtml
@model IEnumerable<BusTicketWebApp.Models.SearchList>

@{
    ViewBag.Title = "SearchResult";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@Html.Partial("_LeftMenu")

<div class="col-xs-10">
    <div class="row">
        <div class="col-xs-3 search_result_nav_div">
            <h4>Search Results</h4>
        </div>
        <div class="col-xs-offset-6 col-xs-2 date_time_today_div">
            <p id="date_time_today"><i class="fa fa-calendar" aria-hidden="true"></i>  @DateTime.Now.ToString("dd/MM/yyyy") (@DateTime.Now.DayOfWeek)</p>
        </div>
        @*<div class="col-xs-offset-8 col-xs-2">
            <a href="/Orders/GenerateSearchPdf?BoardingFromDate=@ViewBag.BoardingFromDate&BoardingToDate=@ViewBag.BoardingToDate&OrderFromDate=@ViewBag.OrderFromDate&OrderToDate=@ViewBag.OrderToDate&Route=@ViewBag.Route&OrderNo=@ViewBag.OrderNo&Type=@ViewBag.Type&GmoOrderNo=@ViewBag.GmoOrderNo&Flight=@ViewBag.Flight&PaymentMethod=@ViewBag.PaymentMethod&BoardingPlace=@ViewBag.BoardingPlace&MemberId=@ViewBag.MemberId&LastName=@ViewBag.LastName&FirstName=@ViewBag.FirstName&Status=@ViewBag.Status&Telephone=@ViewBag.Telephone&Email=@ViewBag.Email" style="display:block; padding:10px;margin-top: 20px;">download pdf</a>
        </div>*@
    </div>
    <div class="row">
        <div class="search_table">
            <input type="checkbox" id="select_all_check_box" /> Select All
            <table class="table table-bordered" id="search_result_table">
                <thead>
                    <tr>
                        <th></th>
                        <th scope="col">#</th>
                        <th scope="col">Order No</th>
                        <th scope="col">Order Date</th>
                        <th scope="col">Ticket Type</th>
                        <th scope="col">Purchaser</th>
                        <th>Adult</th>
                        <th>Child</th>
                        <th>Date of Use</th>
                        <th scope="col">Ticket Status</th>
                        <th scope="col">Order Details</th>
                    </tr>
                </thead>
                <tbody>
                    @{ int count = 1;}
                    @foreach (var x in Model)
                    { 
                    <tr>
                        <td><input type="checkbox" id="single_checkbox_@x.OrderId" value="@x.OrderId" name="ck_change" data-status="@x.StatusId" /></td>
                        <td>@count</td>
                        <td><a href="#">@x.OrderNo</a></td>
                        <td>@x.OrderDate</td>
                        <td>@x.TicketType</td>
                        <td><a href="#">@x.Purchaser</a><a href="mailto:@x.Email" style="display:block;padding:5px"><span class="glyphicon glyphicon-envelope" aria-hidden="true"></span></a></td>
                        <td>@x.NumberOfAdult</td>
                        <td>@x.NumberOfChild</td>
                        <td>@x.DateOfUse</td>
                        @if (x.StatusId == "1")
                        {
                            <td><span class="text-primary-custom status_mark">@x.Status</span></td>
                        }
                        else if (x.StatusId == "2")
                        {
                            <td><span class="text-info-custom status_mark">@x.Status</span></td>
                        }
                        else if (x.StatusId == "3")
                        {
                            <td><span class="text-success-custom status_mark">@x.Status</span></td>
                        }
                        else if (x.StatusId == "4")
                        {
                            <td><span class="text-warning-custom status_mark">@x.Status</span></td>
                        }
                        else
                        {
                            <td><span class="text-muted-custom status_mark">@x.Status</span></td>
                        }

                        <td><a href="javascript:void();" class="o_details" data-id="@x.OrderId" data-url='@Url.Action("OrderDetails","Orders")'>details</a></td>

                    </tr>
                        count++;
                    }
                </tbody>
            </table>

        </div>
    </div>
    <div class="row">
        <div class="col-xs-12 status_chang_div">
            <div class="col-xs-12">
                <p style="font-weight:bold">Change Status</p>
            </div>
            <div class="col-xs-3">

                <select class="form-control" id="status_change_sl">
                    <option value="">Select Status</option>
                    @foreach (var item in ViewBag.Status)
                    {
                        <option value="@item.Id">@item.statusName</option>
                    }
                </select>
            </div>
            <div class="col-xs-2">
                <button id="status_change_btn" class="btn btn-info">change</button>
            </div>
            <div class="col-lg-offset-5 col-xs-1">
                <button id="status_change_btn" class="btn btn-default"><i class="fa fa-print" aria-hidden="true"></i> Print PDF</button>
            </div>
            <div class="col-xs-1">
                <button id="status_change_btn" class="btn btn-default"><i class="fa fa-print" aria-hidden="true"></i> Print CSV </button>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-xs-offset-2 col-xs-7">
            <div class="modal fade" id="order_details_modal" role="dialog">
                @*</div>*@
            <!-- The modal -->
            @*<div class="modal fade" id="flipFlop" tabindex="-1" role="dialog" aria-labelledby="modalLabel" aria-hidden="true">*@
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h4 class="modal-title" id="modalLabel">Order Details</h4>
                    </div>
                    <div class="modal-body" id="order_details_modal_body">

                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
</div>

@section scripts{
    <script type="text/javascript">
        $(document).ready(function () {
            var selected_rows = [];
            $('#search_result_table').dataTable();


            $('#select_all_check_box').on('click', function () {
                var check_all_value = $('#select_all_check_box').is(':checked');
                if (check_all_value) {
                    $('#search_result_table input:checkbox').prop('checked', check_all_value);
                }
                else {
                    $('#search_result_table input:checkbox').prop('checked', check_all_value);
                }
            });


            $('#search_result_table').on('click', '.o_details', function () {

                var id = $(this).data('id');
                var url = $(this).data('url') + '/' + id;
                console.log(url);
                $.get(url, function (data) {
                    $('#order_details_modal_body').html(data);
                    $('#order_details_modal').modal('show');
                });
            });

            $('#status_change_btn').on('click', function () {
                selected_rows = [];
                let selectedOrderAsString = '';

                $("#search_result_table tbody tr td input:checkbox[name=ck_change]:checked").each(function () {
                    selected_rows.push($(this).val());
                });

                var valueOfSelect = $('#status_change_sl').val();
                if (valueOfSelect == null || valueOfSelect == "") {
                    alert("Select Status");
                    return false;
                }
                else if (selected_rows.length <= 0) {
                    alert("Select Order");
                    return false;
                }
                else if (valueOfSelect == "5") {
                    selected_rows = [];
                    $("#search_result_table tbody tr td input:checkbox[name=ck_change]:checked").each(function () {
                        var elementVal = $(this).attr('data-status');
                        
                        if (elementVal == "1" || elementVal == "2") {
                            selected_rows.push($(this).val());
                            selectedOrderAsString += $(this).val() + ",";
                        }
                        else {
                            $(this).prop('checked', false);
                        }
                       
                    });
                }
                else {
                    selected_rows = [];
                    $("#search_result_table tbody tr td input:checkbox[name=ck_change]:checked").each(function () {
                        selected_rows.push($(this).val());
                        selectedOrderAsString += $(this).val() + ",";
                    });
                }

                

                if (selected_rows.length > 0) {
                    $.ajax({
                        type: 'POST',
                        url: '@Url.Action("AlterOrderStatus", "Orders")',
                        data: {
                            orderdata: selectedOrderAsString,
                            statusId : valueOfSelect
                        },
                        success: function (data) {
                            console.log(data);
                            if (data.Status == 'ok') {
                                alert(data.Message);
                                location.reload(true);
                            }
                            else {
                                alert(data.Message);
                                location.reload(true);
                            }

                        },
                        complete: {
                        }
                    });
                }
            });
           


        });
    </script>
}